# Generated by Django 4.2.3 on 2023-07-21 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('sender', models.CharField(max_length=100)),
                ('recipient', models.CharField(max_length=100)),
                ('current_status', models.CharField(max_length=50)),
                ('delivery_address', models.CharField(max_length=200)),
                ('completion_status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed')], default='pending', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
